# These are supported funding model platforms

github: [sionpardosi] # Menggunakan username GitHub Sponsors Anda
patreon: # Tambahkan username Patreon jika ada
open_collective: # Tambahkan username Open Collective jika ada
ko_fi: # Tambahkan username Ko-fi jika ada
tidelift: # Tambahkan nama platform/paket di Tidelift jika ada
community_bridge: # Tambahkan nama proyek Community Bridge jika ada
liberapay: # Tambahkan username Liberapay jika ada
issuehunt: # Tambahkan username IssueHunt jika ada
lfx_crowdfunding: # Tambahkan nama proyek LFX Crowdfunding jika ada
polar: # Tambahkan username Polar jika ada
buy_me_a_coffee: # Tambahkan username Buy Me a Coffee jika ada
thanks_dev: # Tambahkan username Thanks.dev jika ada
custom: # Tambahkan hingga 4 URL sponsorship kustom jika ada
