providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate",
  "./venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "./venv/bin/gunicorn app:app"
